
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql.railway.internal
      DB_PORT: 3306
      DB_NAME: railway
      DB_USER: root
      DB_PASSWORD: ijmYIzmbhdlBkfQnzARVzMxSjDdxPqeC

volumes:
  mysql-data:
